// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB_First_Using_EF_Core_Power_Tools.Models;

public partial class CustomerAndSuppliersByCity
{
    public string City { get; set; }

    public string CompanyName { get; set; }

    public string ContactName { get; set; }

    public string Relationship { get; set; }
}