// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB_First_Using_EF_Core_Power_Tools.Models
{
    public partial class TenMostExpensiveProductsResult
    {
        [StringLength(40)]
        public string TenMostExpensiveProducts { get; set; }
        [Column("UnitPrice", TypeName = "money")]
        public decimal? UnitPrice { get; set; }
    }
}
